Traceback (most recent call last):
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jvanscho/miniforge3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.model_selection import train_test_split
no2 = oml.datasets.get_dataset(547)
X, y, _, _ = no2.get_data(target=no2.default_target_attribute, dataset_format='dataframe');
X = X.drop('day',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/0t/5d8ttqzd773fy0wq3h5db0xr0000gn/T/ipykernel_3566/2904260328.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mmodel_selection[0m [0;32mimport[0m [0mtrain_test_split[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mno2[0m [0;34m=[0m [0moml[0m[0;34m.[0m[0mdatasets[0m[0;34m.[0m[0mget_dataset[0m[0;34m([0m[0;36m547[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mX[0m[0;34m,[0m [0my[0m[0;34m,[0m [0m_[0m[0;34m,[0m [0m_[0m [0;34m=[0m [0mno2[0m[0;34m.[0m[0mget_data[0m[0;34m([0m[0mtarget[0m[0;34m=[0m[0mno2[0m[0;34m.[0m[0mdefault_target_attribute[0m[0;34m,[0m [0mdataset_format[0m[0;34m=[0m[0;34m'dataframe'[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mX[0m [0;34m=[0m [0mX[0m[0;34m.[0m[0mdrop[0m[0;34m([0m[0;34m'day'[0m[0;34m,[0m[0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mX_train[0m[0;34m,[0m [0mX_test[0m[0;34m,[0m [0my_train[0m[0;34m,[0m [0my_test[0m [0;34m=[0m [0mtrain_test_split[0m[0;34m([0m[0mX[0m[0;34m,[0m [0my[0m[0;34m,[0m [0mtrain_size[0m[0;34m=[0m[0;36m0.8[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/openml/datasets/dataset.py[0m in [0;36mget_data[0;34m(self, target, include_row_id, include_ignore_attribute, dataset_format)[0m
[1;32m    696[0m             [0mList[0m [0mof[0m [0mattribute[0m [0mnames[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    697[0m         """
[0;32m--> 698[0;31m         [0mdata[0m[0;34m,[0m [0mcategorical[0m[0;34m,[0m [0mattribute_names[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_load_data[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    699[0m [0;34m[0m[0m
[1;32m    700[0m         [0mto_exclude[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/openml/datasets/dataset.py[0m in [0;36m_load_data[0;34m(self)[0m
[1;32m    542[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    543[0m                 [0;32mwith[0m [0mopen[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mdata_pickle_file[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m [0;32mas[0m [0mfh[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 544[0;31m                     [0mdata[0m[0;34m,[0m [0mcategorical[0m[0;34m,[0m [0mattribute_names[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mfh[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    545[0m         [0;32mexcept[0m [0mFileNotFoundError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    546[0m             [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34mf"Cannot find file for dataset {self.name} at location '{fpath}'."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/Users/jvanscho/miniforge3/lib/python3.9/site-packages/pandas/_libs/internals.cpython-39-darwin.so'>
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/Users/jvanscho/miniforge3/lib/python3.9/site-packages/pandas/_libs/internals.cpython-39-darwin.so'>

